"""add_reputation_system

Revision ID: 082424dbb0ec
Revises: 96527e023c28
Create Date: 2025-12-14 23:42:19.484714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '082424dbb0ec'
down_revision: Union[str, Sequence[str], None] = '96527e023c28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon_url', sa.Text(), nullable=True),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.Column('condition_type', sa.String(length=50), nullable=False),
    sa.Column('condition_value', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('unlocked_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_achievements_unq', 'user_achievements', ['user_id', 'achievement_id'], unique=True)
    op.add_column('users', sa.Column('xp', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('users', sa.Column('level', sa.Integer(), server_default=sa.text('1'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'level')
    op.drop_column('users', 'xp')
    op.drop_index('ix_user_achievements_unq', table_name='user_achievements')
    op.drop_table('user_achievements')
    op.drop_table('achievements')
    # ### end Alembic commands ###
