"""add_dynamic_topics

Revision ID: 20a5921ed7cf
Revises: add_forum_chat
Create Date: 2025-12-04 23:33:36.858050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20a5921ed7cf'
down_revision: Union[str, Sequence[str], None] = 'add_forum_chat'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('forum_posts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('forum_topics', sa.Column('tmdb_id', sa.Integer(), nullable=True))
    op.add_column('forum_topics', sa.Column('media_type', sa.String(length=10), nullable=True))
    op.alter_column('forum_topics', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('tmdb_cache_tmdb_genero_unq'), 'tmdb_cached_filmes', type_='unique')
    op.create_index('tmdb_cache_tmdb_genero_unq', 'tmdb_cached_filmes', ['tmdb_id', 'genero_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('tmdb_cache_tmdb_genero_unq', table_name='tmdb_cached_filmes')
    op.create_unique_constraint(op.f('tmdb_cache_tmdb_genero_unq'), 'tmdb_cached_filmes', ['tmdb_id', 'genero_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('forum_topics', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('forum_topics', 'media_type')
    op.drop_column('forum_topics', 'tmdb_id')
    op.alter_column('forum_posts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('chat_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
