"""Add chat likes

Revision ID: 96527e023c28
Revises: 20a5921ed7cf
Create Date: 2025-12-05 00:37:15.523374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96527e023c28'
down_revision: Union[str, Sequence[str], None] = '20a5921ed7cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('chat_likes_message_idx', 'chat_likes', ['message_id'], unique=False)
    op.create_index('ix_chat_likes_user_message_unq', 'chat_likes', ['user_id', 'message_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chat_likes_user_message_unq', table_name='chat_likes')
    op.drop_index('chat_likes_message_idx', table_name='chat_likes')
    op.drop_table('chat_likes')
    # ### end Alembic commands ###
