"""init schema

Revision ID: ee4f6f0f094d
Revises: 
Create Date: 2025-10-21 19:39:16.684826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ee4f6f0f094d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    
    op.execute("CREATE EXTENSION IF NOT EXISTS citext;")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")
    
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filmes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.Text(), nullable=False),
    sa.Column('titulo_original', sa.Text(), nullable=True),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('poster_path', sa.Text(), nullable=True),
    sa.Column('backdrop_path', sa.Text(), nullable=True),
    sa.Column('media_avaliacao', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('votos', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tmdb_id')
    )
    op.create_index('filmes_titulo_trgm', 'filmes', ['titulo'], unique=False, postgresql_using='gin', postgresql_ops={'titulo': 'gin_trgm_ops'})
    op.create_table('generos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.Column('nome_original', sa.Text(), nullable=True),
    sa.Column('primeira_exibicao', sa.Date(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('poster_path', sa.Text(), nullable=True),
    sa.Column('backdrop_path', sa.Text(), nullable=True),
    sa.Column('media_avaliacao', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('votos', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tmdb_id')
    )
    op.create_index('series_nome_trgm', 'series', ['nome'], unique=False, postgresql_using='gin', postgresql_ops={'nome': 'gin_trgm_ops'})
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', postgresql.CITEXT(), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('senha_hash', sa.Text(), nullable=False),
    sa.Column('criado_em', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('comentarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filme_id', sa.Integer(), nullable=True),
    sa.Column('serie_id', sa.Integer(), nullable=True),
    sa.Column('comentario_pai_id', sa.Integer(), nullable=True),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('criado_em', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(filme_id IS NOT NULL AND serie_id IS NULL) OR (filme_id IS NULL AND serie_id IS NOT NULL)', name='comentario_alvo_chk'),
    sa.ForeignKeyConstraint(['comentario_pai_id'], ['comentarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['filme_id'], ['filmes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['serie_id'], ['series.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('comentarios_filme_idx', 'comentarios', ['filme_id'], unique=False)
    op.create_index('comentarios_pai_idx', 'comentarios', ['comentario_pai_id'], unique=False)
    op.create_index('comentarios_serie_idx', 'comentarios', ['serie_id'], unique=False)
    op.create_index('comentarios_user_idx', 'comentarios', ['user_id'], unique=False)
    op.create_table('filme_generos',
    sa.Column('filme_id', sa.Integer(), nullable=False),
    sa.Column('genero_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['filme_id'], ['filmes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['genero_id'], ['generos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('filme_id', 'genero_id')
    )
    op.create_index('filme_generos_filme_idx', 'filme_generos', ['filme_id'], unique=False)
    op.create_index('filme_generos_genero_idx', 'filme_generos', ['genero_id'], unique=False)
    op.create_table('serie_generos',
    sa.Column('serie_id', sa.Integer(), nullable=False),
    sa.Column('genero_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genero_id'], ['generos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['serie_id'], ['series.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('serie_id', 'genero_id')
    )
    op.create_index('serie_generos_genero_idx', 'serie_generos', ['genero_id'], unique=False)
    op.create_index('serie_generos_serie_idx', 'serie_generos', ['serie_id'], unique=False)
    op.create_table('vistos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filme_id', sa.Integer(), nullable=True),
    sa.Column('serie_id', sa.Integer(), nullable=True),
    sa.Column('data_visto', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('favorito', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.CheckConstraint('(filme_id IS NOT NULL AND serie_id IS NULL) OR (filme_id IS NULL AND serie_id IS NOT NULL)', name='visto_alvo_chk'),
    sa.ForeignKeyConstraint(['filme_id'], ['filmes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['serie_id'], ['series.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('vistos_filme_idx', 'vistos', ['filme_id'], unique=False, postgresql_where=sa.text('filme_id IS NOT NULL'))
    op.create_index('vistos_serie_idx', 'vistos', ['serie_id'], unique=False, postgresql_where=sa.text('serie_id IS NOT NULL'))
    op.create_index('vistos_unq_user_filme', 'vistos', ['user_id', 'filme_id'], unique=True, postgresql_where=sa.text('filme_id IS NOT NULL'))
    op.create_index('vistos_unq_user_serie', 'vistos', ['user_id', 'serie_id'], unique=True, postgresql_where=sa.text('serie_id IS NOT NULL'))
    op.create_index('vistos_user_idx', 'vistos', ['user_id'], unique=False)
    op.create_table('likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comentario_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['comentario_id'], ['comentarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_likes_user_comentario_unq', 'likes', ['user_id', 'comentario_id'], unique=True)
    op.create_index('likes_comentario_idx', 'likes', ['comentario_id'], unique=False)
    op.create_index('likes_user_idx', 'likes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('likes_user_idx', table_name='likes')
    op.drop_index('likes_comentario_idx', table_name='likes')
    op.drop_index('ix_likes_user_comentario_unq', table_name='likes')
    op.drop_table('likes')
    op.drop_index('vistos_user_idx', table_name='vistos')
    op.drop_index('vistos_unq_user_serie', table_name='vistos', postgresql_where=sa.text('serie_id IS NOT NULL'))
    op.drop_index('vistos_unq_user_filme', table_name='vistos', postgresql_where=sa.text('filme_id IS NOT NULL'))
    op.drop_index('vistos_serie_idx', table_name='vistos', postgresql_where=sa.text('serie_id IS NOT NULL'))
    op.drop_index('vistos_filme_idx', table_name='vistos', postgresql_where=sa.text('filme_id IS NOT NULL'))
    op.drop_table('vistos')
    op.drop_index('serie_generos_serie_idx', table_name='serie_generos')
    op.drop_index('serie_generos_genero_idx', table_name='serie_generos')
    op.drop_table('serie_generos')
    op.drop_index('filme_generos_genero_idx', table_name='filme_generos')
    op.drop_index('filme_generos_filme_idx', table_name='filme_generos')
    op.drop_table('filme_generos')
    op.drop_index('comentarios_user_idx', table_name='comentarios')
    op.drop_index('comentarios_serie_idx', table_name='comentarios')
    op.drop_index('comentarios_pai_idx', table_name='comentarios')
    op.drop_index('comentarios_filme_idx', table_name='comentarios')
    op.drop_table('comentarios')
    op.drop_table('users')
    op.drop_index('series_nome_trgm', table_name='series', postgresql_using='gin', postgresql_ops={'nome': 'gin_trgm_ops'})
    op.drop_table('series')
    op.drop_table('generos')
    op.drop_index('filmes_titulo_trgm', table_name='filmes', postgresql_using='gin', postgresql_ops={'titulo': 'gin_trgm_ops'})
    op.drop_table('filmes')
    # ### end Alembic commands ###
